apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - rolearn: arn:aws:iam::227705940501:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-10T02:35:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "37565"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c610e092-94e9-40c1-aaca-7127cfc36bdf
