apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::227705940501:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build    \n- groups:\n  - system:bootstrappers\n  - system:nodes\n
    \ rolearn: arn:aws:iam::227705940501:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1M8PVTCHMBEQB\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-11T23:10:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "20618"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f95e5ef1-b730-44a2-b711-dff1736b00fc
