"""empty message

Revision ID: 403d54badf36
Revises: 84dbdb71a8cf
Create Date: 2020-09-13 08:55:21.949533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403d54badf36'
down_revision = '84dbdb71a8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
